### ISSUE TITLE
Issue with compile method

### ISSUE THREAD

**Issue by xxrraa** [moiseshorta/MelSpecVAE#3]
Hey, "MelSpecVAE" has been working fine up until a few days ago.  All of a sudden the compile method has started throwing an error.  The error is due to this specific part of the compile method.  

**metrics=[_calculate_kl_loss, _calculate_reconstruction_loss]**

When I replace the contents of the list with "accuracy" the error does not appear.

The error says:

**'method' object has no attribute '_from_serialized'**

Thank you for your help :)

**Comment by moiseshorta** [comment]
Problem was due to general update in tensorflow version in Google colab.

Should work now.

**Comment by doktorbanana** [comment]
Hi, i have the same problem with Tensorflow 2.8.0. Is there a fix?
