### ISSUE TITLE
Generated sample length

### ISSUE THREAD

**Issue by smithee771** [moiseshorta/MelSpecVAE#4]
Hi Moises! first of all thanks for your code.
Is there any way to make the generated samples longer?
thanks in advance

**Comment by smithee771** [comment]
.

**Comment by moiseshorta** [comment]
Hi @smithee77 ,

Thanks for checking out the code.

There is a way to make the generated samples longer, but this would also require you to train on longer samples.

In `train.py` there is a variable called `spec_split` which is by default set to 1.

This variable basically multiplies the sample length. It totally depends on your GPU and RAM, but in Colab you can get away by setting it to 2, which duplicates the default sample length. 

Alternatively, you can play around with the `hop` parameter and lower it, but this will decrease your number of FFT bins.

You can play around with this and see what works for you. 

Let me know how it goes!

**Comment by smithee771** [comment]
Hi @moiseshorta , I closed the thread 'cause it wasn't really an issue :), thanks for your answer.
I 've been playing around doubling SHAPE value to get longer results. I'm not really into VAE architecture, but just worked. Sure your method is more efficient, I'll give it a try.
Thanks again.
